inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb

Style/NumericLiterals:
  Exclude:
    - db/migrate/*.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
