inherit_from: .rubocop_todo.yml

Style/NumericLiterals:
  Exclude:
    - db/migrate/*.rb
    - db/schema.rb

Style/Documentation:
  Exclude:
    - db/migrate/*.rb
    - test/test_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/application.rb
