ruby-cache-key: &ruby-cache-key ruby-v1-{{ checksum "Gemfile.lock" }}
ruby-docker-image: &ruby-docker-image circleci/ruby:2.5.1

version: 2.1

executors:
  ruby_executor:
    docker:
      - image: *ruby-docker-image

commands:
  ruby_bootstrap:
    description: Checkout code and restore gem cache
    steps:
      - checkout
      - restore_cache:
          keys:
            - *ruby-cache-key
            - ruby-v1-

jobs:
  bootstrap:
    description: Install gems
    executor: ruby_executor
    steps:
      - ruby_bootstrap
      - run: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: *ruby-cache-key
          paths:
            - vendor/bundle

  lint:
    description: Run the linter
    executor: ruby_executor
    steps:
      - ruby_bootstrap
      - run: bundle exec rubocop

  # test:
  #   description: Run tests
  #   executor: ruby_executor
  #   steps:
  #     - ruby_bootstrap
  #     - run: bundle exec rake db:create
  #     - run: bundle exec rake test

workflows:
  version: 2
  commit:
    jobs:
      - bootstrap
      - lint:
          requires:
            - bootstrap
      - test:
          requires:
            - bootstrap
