ruby-cache-key: &ruby-cache-key ruby-v3-{{ checksum "Gemfile.lock" }}
ruby-docker-image: &ruby-docker-image negebauer/circleci-ruby

version: 2.1

executors:
  ruby_executor:
    docker:
      - image: *ruby-docker-image
  ruby_postgres_executor:
    docker:
      - image: *ruby-docker-image
      - image: circleci/postgres:9.5-alpine

commands:
  ruby_bootstrap:
    description: Checkout code and restore gem cache
    steps:
      - checkout
      - restore_cache:
          keys:
            - *ruby-cache-key
            - ruby-v3-
      - run: bundle check --path ../vendor/bundle || echo "Missing gems"

jobs:
  bootstrap:
    description: Install gems
    executor: ruby_executor
    steps:
      - ruby_bootstrap
      - run: bundle install
      - save_cache:
          key: *ruby-cache-key
          paths:
            - ../vendor/bundle

  lint:
    description: Run the linter
    executor: ruby_executor
    steps:
      - ruby_bootstrap
      - run: bundle exec rubocop

  annotate:
    description: Check if annotations are updated
    executor: ruby_postgres_executor
    steps:
      - ruby_bootstrap
      - run: bundle exec annotate --models
      - run: test "$(git diff --stat)" != '' && echo "Repo dirty, you need to run annotate" && exit 1

  test:
    description: Run tests
    executor: ruby_postgres_executor
    steps:
      - ruby_bootstrap
      - run: bundle exec rake db:create
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results

workflows:
  version: 2
  commit:
    jobs:
      - bootstrap
      - lint:
          requires:
            - bootstrap
      - annotate:
          requires:
            - bootstrap
      - test:
          requires:
            - bootstrap
